api/urls.py
from django.urls import path
from api import views


app_name = "api"

urlpatterns = [
    path("teachers/", views.teacher_list_view, name="teacher_list"),
    path("students/", views.student_list_view, name="student_list"),
]

core/urls.py
from django.urls import path
from core import views


app_name = "core"

handler404 = "core.views.handle_404_view"


urlpatterns = [
    path("", views.index_view, name="index"),
    path(
        "passwords/reset/",
        views.password_reset_request_view,
        name="password_reset_request",
    ),
    path("support/", views.contact_us_view, name="contact_us"),
    path("users/", views.user_list_view, name="user_list"),
    path("users/create", views.user_create_view, name="user_create"),
    path("users/login", views.user_login_view, name="user_login"),
    path("users/logout", views.user_logout_view, name="user_logout"),
    path("users/<str:username>", views.user_details_view, name="user_details"),
    path("users/<str:username>/delete", views.user_delete_view, name="user_delete"),
    path("users/<str:username>/update", views.user_update_view, name="user_update"),
    path(
        "users/<str:username>/intervals/create",
        views.user_interval_create_view,
        name="user_interval_create",
    ),
    path(
        "users/<str:username>/intervals/<int:pk>/update",
        views.user_interval_update_view,
        name="user_interval_update",
    ),
    path(
        "users/<str:username>/intervals/<int:pk>/delete",
        views.user_interval_delete_view,
        name="user_interval_delete",
    ),
    path(
        "users/<str:username>/intervals/<int:pk>/reserve",
        views.user_interval_reserve_view,
        name="user_interval_reserve",
    ),
    path(
        "users/<str:username>/intervals/<int:pk>/release",
        views.user_interval_release_view,
        name="user_interval_release",
    ),
    #### Courses
    path("courses/", views.index_view, name="course_list"),
    path("courses/create", views.course_create_view, name="course_create"),
    path(
        "courses/<int:course_number>/", views.course_details_view, name="course_details"
    ),
    path(
        "courses/<int:course_number>/update",
        views.course_update_view,
        name="course_update",
    ),
    path(
        "courses/<int:course_number>/add-user",
        views.course_add_user_view,
        name="course_add_user",
    ),
    #### Departments
    path("departments/", views.department_list_view, name="department_list"),
    path("departments/create", views.department_create_view, name="department_create"),
    path(
        "departments/<int:department_number>/",
        views.department_details_view,
        name="department_details",
    ),
    path(
        "departments/<int:department_number>/update",
        views.department_update_view,
        name="department_update",
    ),
]

courseware/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
import notifications.urls


password_reset_email_sent_view = auth_views.PasswordResetDoneView.as_view(
    template_name="password/reset_email_sent.html"
)
password_reset_confirm_view = auth_views.PasswordResetConfirmView.as_view(
    template_name="password/reset_confirm.html"
)
password_reset_complete_view = auth_views.PasswordResetCompleteView.as_view(
    template_name="password/reset_complete.html"
)


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("core.urls")),
        path("api/", include("api.urls")),
        path(
            "passwords/reset/email-sent",
            password_reset_email_sent_view,
            name="password_reset_email_sent",
        ),
        path(
            "passwords/reset/<uidb64>/<token>",
            password_reset_confirm_view,
            name="password_reset_confirm",
        ),
        path(
            "passwords/reset/complete",
            password_reset_complete_view,
            name="password_reset_complete",
        ),
        re_path(
            "^inbox/notifications/",
            include(notifications.urls, namespace="notifications"),
        ),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

templates/department/department_create.html
{% extends 'layout.html' %} 

{% load crispy_forms_tags %} 


{% block head %} 
<title>Department Creation</title>
{% endblock %} 

{% block body %} 
<h2>Create Department</h2>
<form action="{% url 'core:department_create' %}" method="post">
    {% csrf_token %} 
    {{ form|crispy }} 
    <br/>
    <button type="submit">Create</button>
    <a href="{% url 'core:index' %}">
        <button type="button">Back to Homepage</button>
    </a>
</form>
<p>
</p>
{% endblock %} 

templates/department/department_details.html
{% extends 'layout.html' %} 

{% load static %} 
{% load markdown_extras %} 

{% block head %} 
<title>Department #{{ department.department_number }}</title>
{% endblock %} 

{% block body %} 
<h2>Department #{{ department.department_number }} Details:</h2>
<p>
    <b>Name: </b> {{ department.name }}
</p>
<p>
    <b>Description: </b>
    {% if department.description %} 
        <div id="bio">
            {{ department.description | markdown | safe }}
        </div> 
    {% else %} 
    ---
    {% endif %}
</p>
<p>
    <b>Department Number: </b> {{ department.department_number }}
</p>
<p>
    <b>Manager: </b>
    <a href="{% url 'core:user_details' department.manager.username %}">
        {{ department.manager.username }}
    </a>
</p>
{% if request.user.is_authenticated %} 
    {% if request.user == department.manager %} 
        <a href="{% url 'core:department_update' department.department_number %}">
            <button type="button">
                Update Information
            </button>
        </a>
    {% endif %} 
{% endif %}
<br/><br/><br/>
<h3>Courses:</h3>
<ul>
    {% for course in department.courses.all %} 
        <h5>
            <li>
                <a href="{% url 'core:course_details' course.course_number %}">
                    {{ course.name }}
                </a>
            </li>
        </h5>
    {% empty %} 
        <li>No course from this department is already available.</li>
    {% endfor %} 
</ul>
{% endblock %} 

templates/department/department_list.html
{% extends 'layout.html' %} 

{% block head %} 
<title>Departments</title>
{% endblock %} 


{% block body %} 
<div>
    <h4>Search in Departments:</h4> 
    <form action="{% url 'core:department_list' %}" method="get">
        <input name="q" />
        <button type="submit">Search</button>
        {% if 'q' in request.GET %} 
        Showing results for: "{{ q }}"
        {% endif %} 
    </form>
</div>
<hr>
<h2>Departments:</h2>
<div>
    <ul>
        {% for department in departments %} 
        <h5><a href="{% url 'core:department_details' department.department_number %}">
            <li>{{ department.name }}</li>
        </a></h5>
        {% empty %}
        <li>No departments at the moment...</li>        
        {% endfor %} 
    </ul>
</div>
{% endblock %} 

templates/department/department_update.html
{% extends 'layout.html' %} 

{% load crispy_forms_tags %} 


{% block head %} 
<title>Update</title>
{% endblock %} 


{% block body %} 
<h2>Update Department:</h2>
<form action="{% url 'core:department_update' department.department_number %}" method="post">
    {% csrf_token %} 
    {{ form|crispy }}
    <button type="submit">Update</button>
    <a href="{% url 'core:department_details' department.department_number %}">
        <button type="button">Back to Department</button>
    </a>
</form>
{% endblock %} 