api/urls.py
from django.urls import path
from api import views


app_name = "api"

urlpatterns = [
    path("teachers/", views.teacher_list_view, name="teacher_list"),
    path("students/", views.student_list_view, name="student_list"),
]

core/urls.py
from django.urls import path
from core import views


app_name = "core"

handler404 = "core.views.handle_404_view"


urlpatterns = [
    path("", views.index_view, name="index"),
    path(
        "passwords/reset/",
        views.password_reset_request_view,
        name="password_reset_request",
    ),
    path("support/", views.contact_us_view, name="contact_us"),
    path("users/", views.user_list_view, name="user_list"),
    path("users/create", views.user_create_view, name="user_create"),
    path("users/login", views.user_login_view, name="user_login"),
    path("users/logout", views.user_logout_view, name="user_logout"),
    path("users/<str:username>", views.user_details_view, name="user_details"),
    path("users/<str:username>/delete", views.user_delete_view, name="user_delete"),
    path("users/<str:username>/update", views.user_update_view, name="user_update"),
    path(
        "users/<str:username>/intervals/create",
        views.user_interval_create_view,
        name="user_interval_create",
    ),
    path(
        "users/<str:username>/intervals/<int:pk>/update",
        views.user_interval_update_view,
        name="user_interval_update",
    ),
    path(
        "users/<str:username>/intervals/<int:pk>/delete",
        views.user_interval_delete_view,
        name="user_interval_delete",
    ),
    path(
        "users/<str:username>/intervals/<int:pk>/reserve",
        views.user_interval_reserve_view,
        name="user_interval_reserve",
    ),
    path(
        "users/<str:username>/intervals/<int:pk>/release",
        views.user_interval_release_view,
        name="user_interval_release",
    ),
    #### Courses
    path("courses/", views.index_view, name="course_list"),
    path("courses/create", views.course_create_view, name="course_create"),
    path(
        "courses/<int:course_number>/", views.course_details_view, name="course_details"
    ),
    path(
        "courses/<int:course_number>/update",
        views.course_update_view,
        name="course_update",
    ),
    path(
        "courses/<int:course_number>/add-user",
        views.course_add_user_view,
        name="course_add_user",
    ),
    #### Departments
    path("departments/", views.department_list_view, name="department_list"),
    path("departments/create", views.department_create_view, name="department_create"),
    path(
        "departments/<int:department_number>/",
        views.department_details_view,
        name="department_details",
    ),
    path(
        "departments/<int:department_number>/update",
        views.department_update_view,
        name="department_update",
    ),
]

courseware/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
import notifications.urls


password_reset_email_sent_view = auth_views.PasswordResetDoneView.as_view(
    template_name="password/reset_email_sent.html"
)
password_reset_confirm_view = auth_views.PasswordResetConfirmView.as_view(
    template_name="password/reset_confirm.html"
)
password_reset_complete_view = auth_views.PasswordResetCompleteView.as_view(
    template_name="password/reset_complete.html"
)


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("core.urls")),
        path("api/", include("api.urls")),
        path(
            "passwords/reset/email-sent",
            password_reset_email_sent_view,
            name="password_reset_email_sent",
        ),
        path(
            "passwords/reset/<uidb64>/<token>",
            password_reset_confirm_view,
            name="password_reset_confirm",
        ),
        path(
            "passwords/reset/complete",
            password_reset_complete_view,
            name="password_reset_complete",
        ),
        re_path(
            "^inbox/notifications/",
            include(notifications.urls, namespace="notifications"),
        ),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

templates/contact_us.html
{% extends 'layout.html' %} 

{% load crispy_forms_tags %} 


{% block head %} 
<title>Contact Us</title>
{% endblock %} 


{% block body %} 
<form action="{% url 'core:contact_us' %}" method="post">
    {% csrf_token %} 
    {{ form|crispy }}
    <button type="submit">Send</button>
    <a href="{% url 'core:index' %}"><button type="button">Back to Homepage</button></a>
</form>

{% endblock %}

templates/index.html
{% extends 'layout.html' %} 

{% load static %} 


{% load static %} 


{% block head %} 
<title>Home Page</title>
{% endblock %} 


{% block body %} 
<div>
    <h4>Search in Courses:</h4> 
    <form action="{% url 'core:course_list' %}" method="get">
        <input name="q" />
        <button type="submit">Search</button>
        {% if 'q' in request.GET %} 
        Showing results for: "{{ q }}"
        {% endif %} 
    </form>
</div>
<hr>
<h2>Courses:</h2>
<p> 
    <ul>
        {% for course in courses %} 
            <li class="course-link">
                <h5>
                    <a href="{% url 'core:course_details' course.course_number %}">
                        {{ course.name }} ---- {{ course.department.name }} ---- Mr/Ms {{ course.teacher.last_name }} ---- {{ course.first_day }}/{{ course.second_day }} ---- {{ course.start_time}} - {{ course.end_time }} 
                    </a>
                </h5>
            </li>
        {% empty %} 
            No Courses available at the moment...
        {% endfor %} 
    </ul>
</p>
{% endblock %} 

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link rel="icon" href="{% static 'logo.png' %}" type="image/x-icon" />
    {% block head %} {% endblock %}
  </head>
  <body>
    <div class="container" style="text-align: center">
      <h1 id="main-header">
        <a href="{% url 'core:index' %}">Courseware WebApp</a>
      </h1>
      {% for message in messages %}
      <div id="messages" class="container-fluid p-0">
        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
          {{ message }}
        </div>
      </div>
      {% endfor %}
      {% if request.user.is_authenticated %} 
        {% for notification in request.user.notifications.unread %}
          <div id="notifications" class="container-fluid p-0">
            <div class="alert alert-info alert-dismissible" role="alert">
              Message from {{ notification.actor }}:<br/>
              {{ notification.description }}
              {{ notification.mark_as_read }}
            </div>
          </div>
        {% endfor %}
      {% endif %}
      <div id="user-hello">
        {% if request.user.is_authenticated %}
        <b>Hello {{ request.user.username|title }},</b><br />
        {% if request.user.is_staff %}
        <b>You are signed in as a Teacher.</b>
        {% else %}
        <b>You are signed in as a Student.</b>
        {% endif %}
        <b></b>
        <br /><br />
        <a href="{% url 'core:user_details' request.user.username %}">
          <button type="button">Profile</button>
        </a>
        {% if request.user.is_superuser %}
        <a href="{% url 'core:course_create' %}">
          <button type="button">Create Course</button>
        </a>
        <a href="{% url 'core:department_create' %}">
          <button type="button">Create Department</button>
        </a>
        {% endif %} {% if request.user.is_staff %}
        <a href="{% url 'core:user_interval_create' request.user.username %}">
          <button type="button">Create Interval</button>
        </a>
        {% endif %}
        <a href="{% url 'core:user_logout' %}">
          <button type="button">Logout</button>
        </a>
        {% else %}
        <b>You are not signed in.</b><br /><br />
        <a href="{% url 'core:user_login' %}">
          <button type="button">Login</button>
        </a>
        <a href="{% url 'core:user_create' %}">
          <button type="button">Register</button>
        </a>
        {% endif %}
        <br /><br />
        <a href="{% url 'core:course_list' %}">
          <button type="button">Courses</button>
        </a>
        <a href="{% url 'core:user_list' %}">
          <button type="button">Users</button>
        </a>
        <a href="{% url 'core:department_list' %}">
          <button type="button">Departments</button>
        </a>
      </div>
      <hr />
    </div>
    <div class="container">{% block body %} {% endblock %}</div>
    <div class="container" style="text-align: center">
      <hr />
      <a href="{% url 'core:contact_us' %}">
        <button type="button">Contact Us</button>
      </a>
    </div>
    <br/><br/><br/><br/>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
      integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js"
      integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK"
      crossorigin="anonymous"
    ></script>
  </body>
</html>