api/urls.py
from django.urls import path
from api import views


app_name = "api"

urlpatterns = [
    path("teachers/", views.teacher_list_view, name="teacher_list"),
    path("students/", views.student_list_view, name="student_list"),
]

core/urls.py
from django.urls import path
from core import views


app_name = "core"

handler404 = "core.views.handle_404_view"


urlpatterns = [
    path("", views.index_view, name="index"),
    path(
        "passwords/reset/",
        views.password_reset_request_view,
        name="password_reset_request",
    ),
    path("support/", views.contact_us_view, name="contact_us"),
    path("users/", views.user_list_view, name="user_list"),
    path("users/create", views.user_create_view, name="user_create"),
    path("users/login", views.user_login_view, name="user_login"),
    path("users/logout", views.user_logout_view, name="user_logout"),
    path("users/<str:username>", views.user_details_view, name="user_details"),
    path("users/<str:username>/delete", views.user_delete_view, name="user_delete"),
    path("users/<str:username>/update", views.user_update_view, name="user_update"),
    path(
        "users/<str:username>/intervals/create",
        views.user_interval_create_view,
        name="user_interval_create",
    ),
    path(
        "users/<str:username>/intervals/<int:pk>/update",
        views.user_interval_update_view,
        name="user_interval_update",
    ),
    path(
        "users/<str:username>/intervals/<int:pk>/delete",
        views.user_interval_delete_view,
        name="user_interval_delete",
    ),
    path(
        "users/<str:username>/intervals/<int:pk>/reserve",
        views.user_interval_reserve_view,
        name="user_interval_reserve",
    ),
    path(
        "users/<str:username>/intervals/<int:pk>/release",
        views.user_interval_release_view,
        name="user_interval_release",
    ),
    #### Courses
    path("courses/", views.index_view, name="course_list"),
    path("courses/create", views.course_create_view, name="course_create"),
    path(
        "courses/<int:course_number>/", views.course_details_view, name="course_details"
    ),
    path(
        "courses/<int:course_number>/update",
        views.course_update_view,
        name="course_update",
    ),
    path(
        "courses/<int:course_number>/add-user",
        views.course_add_user_view,
        name="course_add_user",
    ),
    #### Departments
    path("departments/", views.department_list_view, name="department_list"),
    path("departments/create", views.department_create_view, name="department_create"),
    path(
        "departments/<int:department_number>/",
        views.department_details_view,
        name="department_details",
    ),
    path(
        "departments/<int:department_number>/update",
        views.department_update_view,
        name="department_update",
    ),
]

courseware/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
import notifications.urls


password_reset_email_sent_view = auth_views.PasswordResetDoneView.as_view(
    template_name="password/reset_email_sent.html"
)
password_reset_confirm_view = auth_views.PasswordResetConfirmView.as_view(
    template_name="password/reset_confirm.html"
)
password_reset_complete_view = auth_views.PasswordResetCompleteView.as_view(
    template_name="password/reset_complete.html"
)


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("core.urls")),
        path("api/", include("api.urls")),
        path(
            "passwords/reset/email-sent",
            password_reset_email_sent_view,
            name="password_reset_email_sent",
        ),
        path(
            "passwords/reset/<uidb64>/<token>",
            password_reset_confirm_view,
            name="password_reset_confirm",
        ),
        path(
            "passwords/reset/complete",
            password_reset_complete_view,
            name="password_reset_complete",
        ),
        re_path(
            "^inbox/notifications/",
            include(notifications.urls, namespace="notifications"),
        ),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

templates/user/user_create.html
{% extends 'layout.html' %} 
{% load crispy_forms_tags %}


{% block head %} 
<title>Registeration</title>
{% endblock %} 

{% block body %} 
<h2>Create User:</h2>
<form action="{% url 'core:user_create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %} 
    {{ form|crispy }} 
    <br/>
    Role: <select name="title">
        <option>Teacher</option>
        <option>Student</option>
    </select><br/><br/>
    <button type="submit">Register</button>
    <a href="{% url 'core:index' %}">
        <button type="button">Back to Homepage</button>
    </a>
</form>
<br/><br/>
<p>
    Already have an account? <a href="{% url 'core:user_login' %}">Login</a>.
</p>
{% endblock %} 

templates/user/user_delete.html
{% extends 'layout.html' %} 
{% load static %} 


{% block head %} 
<title>Delete Account</title>
{% endblock %} 


{% block body %} 
<h3>Delete User:</h3>
<br/>
<form action="{% url 'core:user_delete' user.username %}" method="post">
    {% csrf_token %}
    <h4>Are you sure that you are going to <b>DELETE</b> your account and all it's information <b>FOREVER</b>?</h4>
    <br/>
    <a href="{% url 'core:index' %}">
        <button type="button">No! Take me back!</button>
    </a>
    <button type="submit">Yes, Delete my Account</button>
</form>
{% endblock %} 

templates/user/user_details.html
{% extends 'layout.html' %} 

{% load static %} 
{% load markdown_extras %} 


{% block head %} 
<title>Profile</title>
{% endblock %} 

{% block body %} 
<p>
    <b>Profile Photo:</b>
    {% if user.image %} 
        <div>
            <img src="{{ user.image.url }}" alt="User Image"/>
        </div>
    {% else %}
        No Image 
    {% endif %}
    
</p>
<p>
    <b>First Name: </b> 
    {% if user.first_name %}
        {{ user.first_name }}
    {% else %} 
        ---
    {% endif %}
</p>
<p>
    <b>Last Name: </b>
    {% if user.last_name %}
        {{ user.last_name }}
    {% else %} 
        ---
    {% endif %}
</p>

<p>
    <b>Username: </b> {{ user.username }}
</p>
<p>
    <b>Role: </b>
    {% if user.is_staff %} 
    Teacher 
    {% else %} 
    Student
    {% endif %} 
</p>
<p>
    <b>Email: </b> {{ user.email }}
</p>
<p>
    <b>Bio: </b>
    {% if user.bio %} 
        <div id="bio">
            {{ user.bio | markdown | safe }}
        </div> 
    {% else %} 
    ---
    {% endif %}
</p>
<p>
    <b>Gender: </b> {{ user.gender }}
</p>

{% if request.user.is_authenticated %} 
    {% if request.user == user %} 
        <a href="{% url 'core:user_update' user.username %}">
            <button type="button">
                Update Information
            </button>
        </a>
        <br/></br>
    {% endif %} 
    {% if not user.is_staff %} 
    <br/><br/><br/>
    <h3>Participates in:</h3>
        <ul>
            {% for course in user.participated_courses.all %} 
                <a href="{% url 'core:course_details' course.course_number %}">
                    <h5><li>{{ course.name }}</li></h5>
                </a>
            {% empty %} 
                <li>No courses have been added yet.</li>
            {% endfor %} 
        </ul>
    <br/><br/>
    <h3>Reserved Intervals:</h3>
    <ul>
        {% for interval in user.reserved_intervals.all %} 
            <li>
                {{ interval }}
                {% if request.user == user %} 
                <a href="{% url 'core:user_interval_release' username=user.username pk=interval.pk %}">
                    <button type="button">Release</button>
                </a>
                {% endif %} 
            </li> 
        {% empty %} 
            <li>No Intervals have been reserved yet.</li>
        {% endfor %} 
    </ul>
    {% else %}
    <br/><br/>
    <h3>Courses:</h3>
    <ul>
        {% for course in user.courses.all %} 
            <h5>
                <li>
                    <a href="{% url 'core:course_details' course.course_number %}">
                        {{ course.name }}
                    </a>
                </li>
            </h5>
        {% empty %} 
            <li>No Course from this Teacher is available.</li>
        {% endfor %} 
    </ul>
    <br/><br/>
    <h3>Intervals:</h3>
    <ul>
        {% for interval in user.intervals.all %} 
            <li>
                {{ interval.day }} | From: {{ interval.start_time }} To: {{ interval.end_time }} | Capacity: {{ interval.capacity }} | Reserved: {{ interval.reserving_students.count }} 

                {% if not request.user.is_staff %} 
                <a href="{% url 'core:user_interval_reserve' username=user.username pk=interval.pk %}">
                    <button type="button">Reserve</button>
                </a>
                {% elif request.user == user %} 
                <a href="{% url 'core:user_interval_update' username=user.username pk=interval.pk %}">
                    <button type="button">Edit</button>
                </a>
                <a href="{% url 'core:user_interval_delete' username=user.username pk=interval.pk %}">
                    <button style="background-color: red" type="button">Delete</button>
                </a>
                {% endif %}
            </li>    
        {% empty %} 
            <li>No Intervals are available for this teacher.</li>
        {% endfor %} 
    </ul> 
    <a href="{% url 'core:user_interval_create' username=user.username %}"><button type="button">Add Interval</button></a>
    {% endif %}
    <br/><br/>
    {% if request.user == user %} 
    <a href="{% url 'core:user_delete' user.username %}">
        <button style="background-color: red" type="button">Delete Account</button>
    </a>
    {% endif %} 
{% endif %}
{% endblock %} 

templates/user/user_list.html
{% extends 'layout.html' %} 

{% load static %} 


{% block head %}
<title>Users</title>
{% endblock %}

{% block body %} 
<div>
    <h4>Search in Users:</h4> 
    <form action="{% url 'core:user_list' %}" method="get">
        <input name="q" />
        <button type="submit">Search</button>
        {% if 'q' in request.GET %} 
        Showing results for: "{{ q }}"
        {% endif %} 
    </form>
</div>
<hr>
<h2>Teachers:</h2>
<div>
    <ul>
        {% for user in teacher_users %} 
            <li class="user-link">
                <h5>
                    <a href="{% url 'core:user_details' user.username %}">
                        {{ user.username }} --- {{ user.first_name }} {{ user.last_name }}
                    </a>
                </h5>
            </li>
        {% empty %} 
            <li>No Teachers at the moment...</li>
        {% endfor %} 
    </ul>
</div>
<hr>
<h2>Students:</h2>
<div>
    <ul>
        {% for user in student_users %} 
            <li class="user-link">
                <h5>
                    <a href="{% url 'core:user_details' user.username %}">
                        {{ user.username }} --- {{ user.first_name }} {{ user.last_name }}
                    </a>
                </h5>
            </li>
        {% empty %} 
            <li>No Students at the moment...</li>
        {% endfor %} 
    </ul>
</div>
{% endblock %} 

templates/user/user_login.html
{% extends 'layout.html' %} 
{% load crispy_forms_tags %} 


{% block head %} 
<title>Login</title>
{% endblock %} 


{% block body %} 
<h2>Login:</h2>
<form action="{% url 'core:user_login' %}" method="post">
    {% csrf_token %} 
    {{ form|crispy }}
    Forgot Password? 
    <a href="{% url 'core:password_reset_request' %}">
        Reset your password
    </a>.<br/><br/>
    <button type="submit">Login</button>
    <a href="{% url 'core:index' %}">
        <button type="button">Back to Homepage</button>
    </a>
</form>
<br/>
<div>
    Need a new account? <a href="{% url 'core:user_create' %}">Sign up</a>.
</div>
{% endblock %} 

templates/user/user_logout.html
{% extends 'layout.html' %} 

{% load static %} 


{% block head %} 
<title>Logout</title>
{% endblock %} 


{% block body %} 
<form action="{% url 'core:user_logout' %}" method="post">
    {% csrf_token %}
    <h2>Are you sure you want to logout?</h2><br/>
    <a href="{% url 'core:index' %}"><button type="button">No take me back!</button></a>
    <button type="submit">Yes! Log me out!</button>
    
</form>
{% endblock %} 

templates/user/user_update.html
{% extends 'layout.html' %} 

{% load crispy_forms_tags %} 


{% block head %} 
<title>Update</title>
{% endblock %} 


{% block body %} 
<h2>Update Information:</h2>
<form action="{% url 'core:user_update' request.user.username %}" method="post" enctype="multipart/form-data">
    {% csrf_token %} 
    {{ form|crispy }}
    <br/>
    Gender: <select name="gender">
        <option {% if request.user.gender == "Other" %} selected {% endif %}>Other</option>
        <option {% if request.user.gender == "Male" %} selected {% endif %}>Male</option>
        <option {% if request.user.gender == "Female" %} selected {% endif %}>Female</option>
    </select>
    <br/><br/>
    <button type="submit">Update</button>
    <a href="{% url 'core:user_details' request.user.username %}">
        <button type="button">Back to profile</button>
    </a>
</form>
{% endblock %} 